# DSTDGCN
# runner
runner: 3dpw
save:
  path: # path options
    base: runs/ # this needs to be defined in commandline
    files: scripts/
    checkpoints: checkpoints/ # a folder that records all the training and testing results
    tensorboard: tensorboard/ # tensorbard results
    visualize: visualize/
  files: # a list of files to save
    [
      model/dstdgcn.py,
      model/layers/graph.py,
      model/layers/time.py,
      engine/prediction.py,
      runner/pw3d.py,
    ]
train_batch_size: 32
test_batch_size: 32
num_workers: 4
device: cuda
epoch: 100
mode: train # four modes: train, test, train-debug, test-debug

# dataset options
dataset:
  name: 3dpw
  scale: False
  train:
    3dpw:
      data_path: data/3dpw/sequenceFiles/train/
      input_n: 10 # length of input sequence
      output_n: 30 #
      dct_used: 0 # dct dimension, use dct transformation when this is larger than 0
      mirror: True
      padding: True
  test:
    3dpw:
      data_path: data/3dpw/sequenceFiles/test/
      input_n: 10 # length of input sequence
      output_n: 30 #
      dct_used: 0 # dct dimension, use dct transformation when this is larger than 0
      mirror: False
      padding: True

# experiment setting
setting:
  input_n: 10
  output_n: 30
  eval_frame: [4, 9, 14, 19, 24]
  dim_used:
    [
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66,
      67,
      68,
      69,
      70,
      71,
    ]
  joint_to_ignore: null
  joint_to_equal: null
  save: False # save result for each iteration

# model options
# define one randomly, this will not be used
model:
  name: dstdgcn
  load: False
  ckpt: None
  dstdgcn:
    input_channels: 6
    input_time_frame: 10
    output_time_frame: 30
    st_gcnn_dropout: 0.1
    joints_to_consider: 23
    num_feature: 64
    num_layers: 5
    layout: 3dpw

# training engine
engine:
  learn:
    opt: adam
    lr: 3.e-3 # 5.e-3
    beta1: 0.5 # params for Adam optim
    beta2: 0.999 # params for Adam optim
    weight_decay: 1.e-4
    gamma: 0.9 # 0.9 # learning rate decay
    step_size: 5 # 5 # means no learning rate decay
    patience: 5
    factor: 0.5
  loss:
    joint: [jl2, 1] # mpjpe_error on 3d space (l2 loss)
    # gm: [gm2, 1000] # gram matrix loss
    # bone: [bl2, 1] # bone loss
    # transition: [tl2, 1] # transition loss
    # coordinate: [cl1, 1] # joint l1 loss
  n_out: 1
  transform: tsc # dimension tranformation
  use_weight: False # body weights
  inverse: True # inverse
