# DSTDGCN
# runner
runner: h36m
save:
  path: # path options
    base: runs/ # this needs to be defined in commandline
    files: scripts/
    checkpoints: checkpoints/ # a folder that records all the training and testing results
    tensorboard: tensorboard/ # tensorbard results
    visualize: visualize/
  files: # a list of files to save
    [
      model/dstdgcn.py,
      model/layers/graph.py,
      model/layers/time.py,
      engine/prediction.py,
      runner/h36m.py,
    ]
train_batch_size: 32
test_batch_size: 32
num_workers: 4
device: cuda
epoch: 100
mode: visualize

# dataset options
dataset:
  name: h36m
  scale: False
  train:
    h36m:
      data_path: data/h36m
      actions: all
      input_n: 10 # length of input sequence
      output_n: 25 #
      dct_used: 0 # dct dimension, use dct transformation when this is larger than 0
      mode: train # scene selection
      sample_rate: 2 # sample rate
      data_3d: True # load 3D data
      mirror: True
  test:
    h36m:
      data_path: data/h36m/
      input_n: 10 # length of input sequence
      output_n: 25 #
      dct_used: 0 # dct dimension, use dct transformation when this is larger than 0
      mode: test
      sample_rate: 2
      data_3d: True
      test_mode: all
      mirror: False

# experiment setting
setting:
  input_n: 10
  output_n: 25
  eval_frame: [1, 3, 7, 9, 13, 17, 21, 24] # [1, 3, 7, 9]
  dim_used:
    [
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      58,
      59,
      63,
      64,
      65,
      66,
      67,
      68,
      75,
      76,
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      87,
      88,
      89,
      90,
      91,
      92,
    ]
  joint_to_ignore: [16, 20, 23, 24, 28, 31]
  joint_to_equal: [13, 19, 22, 13, 27, 30]
  save: False # save result for each iteration

# model options
model:
  name: dstdgcn
  load: True
  ckpt: runs/20220320_dstdgcn_h36m_train_motion_mirror_rinit/checkpoints/best.pth
  dstdgcn:
    input_channels: 6
    input_time_frame: 10
    output_time_frame: 25
    st_gcnn_dropout: 0.1
    joints_to_consider: 22
    num_feature: 64
    num_layers: 5
    layout: h36m

# training engine
engine:
  learn:
    opt: adam
    lr: 5.e-4
    beta1: 0.5 # params for Adam optim
    beta2: 0.999 # params for Adam optim
    weight_decay: 1.e-4
    gamma: 0.95 # learning rate decay
    step_size: 5 # means no learning rate decay
    patience: 10
    factor: 0.5
  loss:
    joint: [jl2, 1] # mpjpe_error on 3d space
    # gm: [gm2, 1000] # gram matrix loss
    # bone: [bl2, 1] # bone loss
    # transition: [tl2, 1] # transition loss
    # coordinate: [cl1, 1] # joint loss
  n_out: 1
  transform: tsc # dimension tranformation
  use_weight: False # body weights
  inverse: True # inverse
